### ISSUE TITLE
GitHub Desktop - Warning: line endings

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/UnitTest#3]
@sidey79 

Seitdem .gitattributes ergänzt wurde,
kann ich via Software kein "Clone" durchführen normal.

Ständig kommt sofort bei Einbindung
**"Warning: line endings have changed from 'CRLF' to 'LF'**

andere Projekte funktionieren normal wenn .gitattributes File folgenden Inhalt enthält:
```

# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto eol=lf

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.pm text eol=lf
*.pl text eol=lf
*.hash text eol=lf
*.txt text eol=lf
*.sh text eol=lf

# Denote all files that are truly binary and should not be modified.
*.hex binary
*.bin binary
```

Ich vermute, es liegt am unvollständigen Eintrag
`text=auto`

**Comment by sidey79** [comment]
Wir können es anpassen. Wenn die Fehler dann verschwinden :)

Wir sollten Änderungen aber nur noch in fhem/UnitTest machen

**Comment by HomeAutoUser** [comment]
>Wir können es anpassen. Wenn die Fehler dann verschwinden :)

ich HOFFE ES.

Würdest du die Anpassungen vornehmen bitte!?

>Wir sollten Änderungen aber nur noch in fhem/UnitTest machen

Ja gerne, dann aber bitte den Stand anpassen wie hier und dann dieses Repro "schließen" oder mindestens verweisen auf fhem/UnitTest. Solange deines hier immer "neuerer" ist vom Datum her, so kommt man nie auf das neue "gelinkt" *grins* Google greift sich ja aller.
